### PR TITLE
Resolve #1 Support wrap content & padding instead of height/width dp

### LINKED ISSUE #1: Support padding instead of height/width dp
**Is your feature request related to a problem?**

For a balloon with multiple lines of text, having the balloon container scale with its height would be very useful. 

**Describe the solution you'd like:**

At the moment the `layout_balloon.xml` file uses dp values instead of "wrap_content".  If the layout uses "wrap_content" for height, the builder can drop `builder.setHeight()` and `builder.setWidth()`, and instead have something like `builder.setPaddingVert()` and `builder.setPaddingHoriz()`.  

Thoughts?

### PR DESCRIPTION
**Pull request by skydoves**
## Guidelines
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

### Types of changes
What types of changes does your code introduce?

- [x] New feature (non-breaking change which adds functionality)

Wrap content & padding instead of height/width dp.

### CODE REVIEW

**Comment by jeevansurendran** [comment]
Hey @skydoves , how soon can I expect this feature being added to your next release ?

**Comment by skydoves** [comment]
Hi, It is already released in version 1.1.2 (https://github.com/skydoves/Balloon/releases).
 
-----Original Message-----

**Comment by jeevansurendran** [comment]
Thank you ! Any ideas how could i get a shadow effect for the baloon?

**Comment by skydoves** [comment]
Released in [1.1.2](https://github.com/skydoves/Balloon/releases).
Do you mean this dimming effect #14 on the background?

**Comment by jeevansurendran** [comment]
Some what similar to this one
You could see a shadow effect below. I want to bring a similar effect. Should I acheive this using a drawable or is there something supported by the library

**Comment by skydoves** [comment]
Thank you for your idea!
It is already to be featured in the next release :)

screenshot555192197

**Comment by skydoves** [comment]
#21

**Pull request merged**
